# Generated by Django 3.0.6 on 2020-05-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_containers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containers',
            old_name='contianerid',
            new_name='containerid',
        ),
    ]
